import { getServerSession } from "next-auth"
import Link from "next/link";
import Logout from "./logout";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      
      <body>
        <nav>
        {!! session && 
          <Logout />
        } 
        {!session && 
          <Link href="/login">
            Log in
          </Link>
        }
      </nav>
        {children}</body>
    </html>
  )
}
